name: Lab3 Create Artefact
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: npm clean-install
      - run: npm pack
      - name: Upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: node-todo-0.0.0
          path: node-todo-0.0.0.tgz
